server:
  servlet:
    context-path: /richpwd
  port: 8085

spring:
  datasource:
    url: 'jdbc:mysql://127.0.0.1:3306/richpwd'
    username: root
    password: '123456'
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
  #    show-sql: true
  servlet:
    multipart:
      max-file-size: 3MB
      max-request-size: 20MB


richpwd.app.jwtSecret: richpwdSecretKey
# 30分
richpwd.app.jwtExpirationSec: 1800
# 3天
richpwd.app.jwtRefreshExpirationSec: 259200

# 1分鐘
#richpwd.app.jwtExpirationSec: 10
# 5分鐘
#richpwd.app.jwtRefreshExpirationSec: 30
