server:
   servlet:
     context-path: /richpwd
   port: 8085

spring:
  datasource:
    url: 'jdbc:mysql://127.0.0.1:3306/richpwd'
    username: root
    password: '123456'
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
#    show-sql: true